### ISSUE TITLE
Add "log"-property to command runner

### ISSUE THREAD

**Issue by lefinal** [lefinal/lwee#22]
Add a `log` property that is a map of properties to log for runs. These include stuff like:

```yaml
log:
  version:
    run:
      - "/bin/bash"
      - "--version"
```
